//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PARTE 2.rc
//
#define ID_DIAIS                        101
#define ID_DIAREGIS                     103
#define ID_DIAGVP                       104
#define ID_DIAGIU                       105
#define ID_MODIFY_MOD_LISTU             105
#define IDR_MENU1                       106
#define ID_DIAGRESETCON_U_VP            114
#define ID_DIAGLISTU_U_VP               115
#define ID_DIAGALTACLI_CLI_VP           116
#define ID_DIAGLISTCLI_CLI_VP           117
#define ID_DIAGALTAPRO_PRO_VP           118
#define ID_DIAGLISTPRO_PRO_VP           119
#define ID_DIAGALTACONSU_CONSU_VP       120
#define ID_DIAGLISTCONSU_CONSU_VP       121
#define ID_DIAGSALIR_VP                 122
#define ID_DIAGALTAUSU_VP               123
#define ID_IU_VP                        124
#define ID_BUTTEnterIS                  1001
#define ID_BUTTExitIS                   1002
#define ID_ConIS                        1003
#define ID_EDITNomUsuIS                 1004
#define ID_COMBO_COIS                   1005
#define ID_STAPICIS                     1006
#define ID_STATICNomUsuIS               1007
#define ID_STATICConIS                  1008
#define ID_ComIS                        1009
#define ID_BUTTRegisIS                  1010
#define ID_BUTTEnterREGIS               1010
#define ID_BUTTRegINFOUSU               1010
#define ID_BUTTRetREGIS                 1011
#define ID_BUTTSaveIU                   1011
#define ID_EDITNoUsREGIS                1012
#define ID_BUTTFotoIU                   1012
#define ID_STANoUsREGIS                 1013
#define ID_STAConREGIS                  1014
#define ID_STAComREGIS                  1015
#define ID_EDITConREGIS                 1016
#define ID_EDITComREGIS                 1017
#define ID_STAPICREGIS                  1018
#define ID_EDITNomComIU                 1019
#define ID_EDITAliUsuIU                 1020
#define ID_STAPICDIAIU                  1021
#define ID_EDITTEL_ALTACL               1021
#define ID_STAPICIDU                    1022
#define ID_EDITEMAIL_ALTACL             1022
#define ID_STANomComIU                  1023
#define ID_STAAliUsuIU                  1024
#define ID_STA_DB_CLIENTES              1025
#define ID_STANomComIU2                 1025
#define ID_STA_DB_PA                    1026
#define ID_STAAliUsuIU2                 1026
#define ID_STA_DB_PI                    1027
#define ID_STA_DB_TOCONSU               1028
#define ID_STA_DB_TOCOM                 1029
#define ID_RAD_ADMINREGIS               1030
#define ID_RAD_CAJREGIS                 1031
#define ID_BUTTMOD_IU                   1031
#define ID_EDITNOMU_ALTA_U              1032
#define ID_EDITCON_ALTA_U               1033
#define ID_EDITCOM_ALTA_U               1034
#define ID_STATICNOMU_ALTA_U            1035
#define ID_STATICCON_ALTA_U             1036
#define ID_STATICCOM_ALTA_U             1037
#define ID_RADADMIN_ALTA_U              1038
#define ID_RADCAJERO_ALTA_U             1039
#define ID_BUTTREGIS_ALTA_U             1040
#define ID_BUTTREG_ALTA_U               1041
#define ID_EDITCONTRA_RESET             1042
#define ID_BUTTReg_RESET                1043
#define ID_EDITNEWCON_RESET             1044
#define ID_BUTTSAVE_RESET               1045
#define ID_STATICCONTRA_RESET           1046
#define ID_STATICNEWCON_RESET           1047
#define ID_LISTUSU_RESET                1048
#define ID_EDITCOM_RESET                1049
#define ID_STATICCOM_RESET              1050
#define ID_STATIC_RESETTYPE             1051
#define ID_LIST_LISTU                   1053
#define ID_STATICCOM_LIST               1055
#define ID_EDITCOM_LISTU                1056
#define ID_PCICBMP_LISTU                1057
#define ID_STATICNOMCOM_LISTU           1058
#define ID_STATICALIAS_LISTU            1059
#define ID_BUTTUPDATE_LISTU             1060
#define ID_STATICNOMMODI_LISTU          1061
#define ID_BUTTREG_LISTU                1061
#define ID_STAAMOD_LISTU                1062
#define ID_BUTTELI_LISTU                1062
#define ID_EDITNOMMOD_LISTU             1063
#define ID_STATEL_LISTCL                1063
#define ID_EDITAMOD_LISTU               1064
#define ID_STAAL_LISTCL                 1064
#define ID_STAPIC_MOD_LISTU             1065
#define ID_STAAL_LISTCL2                1065
#define ID_BUTTREGMOD_LISTU             1066
#define ID_STATICNOMMODI_LISTU2         1067
#define ID_BUTTPHOTOMOD_LISTU           1068
#define ID_BUTTSAVEMOD_LISTU            1069
#define ID_EDITTYPE_LISTU               1070
#define ID_EDITDATE_LISTCL              1071
#define ID_SAVE_ALTACL                  1072
#define ID_BUTTREG_ALTACL               1073
#define ID_EDITNOMCO_ALTACL             1074
#define ID_EDITAL_ALTACL                1075
#define ID_EDITDATE_ALTACL              1076
#define ID_EDITCOM_LISTCL               1077
#define ID_LIST_LISTCL                  1078
#define ID_STANOMCM_LISTCL              1079
#define ID_STAEMAIL_LISTCL              1080
#define ID_BUTTUPDATE_LISTCL            1081
#define ID_BUTTELI_LISTCL               1082
#define ID_BUTTREG_LISTCL               1083
#define ID_EDITCOM_ALTACL               1084
#define ID_EDITTEL_LISTCL               1085
#define ID_EDITALIAS_LISTCL             1086
#define ID_RADIOACTIVE_ALTAPRO          1086
#define ID_EDITEMAIL_LISTCL             1087
#define ID_RADINACTIVE_ALTAPRO          1087
#define ID_EDITNOMPRO_ALTAPRO           1088
#define ID_EDITALIAS_LISTCL2            1088
#define ID_EDITTOTAL_LISTCONSU          1088
#define ID_EDITMONTO_ALTAPRO            1089
#define ID_EDITPORDES_ALTAPRO           1090
#define ID_EDITDATE_ALTAPRO             1091
#define ID_EDITCOM_ALTAPRO              1092
#define ID_BUTTREG_ALTAPRO              1093
#define ID_BUTTSAVE_ALTAPRO             1094
#define ID_EDITCOM_LISTPRO              1095
#define ID_EDITMONTO_LISTPRO            1096
#define ID_EDITPORDES_LISTPRO           1097
#define ID_EDITSTATUS_LISTPRO           1098
#define ID_LIST_LISTPRO                 1099
#define ID_BUTTUPDATE_LISTPRO           1100
#define ID_BUTTDELETE_LISTPRO           1101
#define ID_BUTTREG_LISTPRO              1102
#define ID_LIST_ALTACONSU               1103
#define ID_EDITMON_ALTACONSU            1104
#define ID_EDITSUB_ALTACONSU            1105
#define ID_EDITDES_ALTACONSU            1106
#define ID_EDITTOTAL_ALTACONSU          1107
#define ID_EDITDATE_ALTACONSU           1108
#define ID_EDITCOM_ALTACONSU            1109
#define ID_BUTTSAVE_ALTACONSU           1110
#define ID_BUTTRES_ALTACONSU            1111
#define ID_STATICNOMCL_LISTCONSU        1112
#define ID_BUTTCHECK_ALTACONSU          1112
#define ID_LIST_LISTCONSU               1113
#define ID_BUTTREG_LISTCONSU            1114
#define ID_EDITCOM_LISTCONSU            1115
#define ID_EDITMON_LISTCONSU            1116
#define ID_EDITSUB_LISTCONSU            1117
#define ID_EDITDES_LISTCONSU            1118
#define ID_NODATE_ALTACONSU             1119
#define ID_EDITCLI_ALTACONSU            1120
#define ID_STATICCLI_ALTACONSU          1121
#define ID_INFORMACIODEUSUARIO_ALTA     40001
#define ID_INFORMACIODEUSUARIO_RESTABLECERCONTRASENA 40002
#define ID_INFORMACIODEUSUARIO_LISTADEUSUARIOS 40003
#define ID_USUARIOS_ALTA                40004
#define ID_USUARIOS_RESTABLECERCONTRASENA 40005
#define ID_USUARIOS_LISTADEUSUARIOS     40006
#define ID_MENU_REFRESHCON              40007
#define ID_CLIENTES_ALTADECLIENTE       40008
#define ID_CLIENTES_LISTADECLIENTE      40009
#define ID_PROMOCIONES_ALTADEPROMOCION  40010
#define ID_PROMOCIONES_LISTADEPROMOCION 40011
#define ID_CONSUMOS_ALTADECONSUMOS      40012
#define ID_CONSUMOS_LISTADECONSUMOS     40013
#define ID_INFORMACIODEUSUARIO_INFROMACION 40014
#define ID_SALIR_SALIR                  40015
#define ID_INFORMACION_IU_VP            40016
#define ID_ALTA_USU_VP                  40017
#define ID_RESETPASS_USU_VP             40018
#define ID_LISTUSU_USU_VP               40019
#define ID_REGISCUSTO_CUSTO_VP          40020
#define ID_LISTCUSTO_CUSTOS_VP          40021
#define ID_PROMOCIONES_LISTADEPROMOCION40022 40022
#define ID_REGSPROM_PROM_VP             40023
#define ID_LISTPROM_PROM_VP             40025
#define ID_REGSCOMP_COMP_VP             40026
#define ID_LISTCOMP_COMP_VP             40027
#define ID_EXIT_EXIT_VP                 40028
#define ID_CS_EXIT_VP                   40030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
